#!/bin/sh

dir=$(dirname $(readlink -f "$0"))

case "$(uname -sr)" in
   CYGWIN*|MINGW*|MINGW32*|MSYS*)
     dir=$(cd "${0%[/\\]*}" > /dev/null; pwd)
     ;;
esac

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

php "${dir}/artisan-root.php" "$@"
